### ISSUE TITLE
make dockerfile

### ISSUE THREAD

**Issue by martinghunt** [iqbal-lab-org/varifier#3]

**Comment by mbhall88** [comment]
Ok. I have spent a lot of today playing with trying to get this image as small as possible. In the end, I think we would be best off just using the image that biocontainers will auto-build when we create a bioconda recipe.  
The reason for this is the smallest version I can create of this image is effectively one that installs all the dependencies with conda (the same way biocontainers effectively does it). I couldn't get an alpine image to work due to the `k8` precompiled binary (which is required by paftools) not being able to run on alpine. I tried building `k8` from source but couldn't get `v8` (it's underlying engine) to build on alpine...

So @martinghunt , when you make the first release we can create a conda recipe and then we get the image for free.
